### ISSUE TITLE
浏览器中有demo吗？

### ISSUE THREAD

**Issue by zywj** [SegmentFault/HyperDown.js#2]
@Integ  浏览器中有demo吗？

**Comment by Integ** [comment]
https://github.com/Integ/BachEditor

用的就是hyperdown

**Comment by ZYWJ** [comment]
这个demo似乎看起来跟现在的hyperdown.js不太一样。不知道有没有像php版那样的简单的两三行示例demo

**Comment by Integ** [comment]
用法和php版本的一样，引入 hyperdown.js , new 一个Parser，调用 makeHtml 方法 传入 markdown文本
 
```
var Parser = require('hyperdown.js');
var parser = new Parser();
console.log(parser.makeHtml('#mdtext#'))
```

**Comment by Integ** [comment]
hyperdown 已升级至1.0.1,
欢迎体验，反馈。

**Comment by stevesgit** [comment]
作者你好，我对前端不太熟悉，按照你上面的代码，require是要要require.js引入代码块是吧？我照着引入后出现了，Uncaught TypeError: parser.makeHtml is not a function的提示，我不知道哪里错了。
贴下代码

`<script type="text/javascript">
$('textarea').bind('input propertychange', function() {
  var Parser = require(['/js/parser.js']);
  var parser = new Parser();
  var a=parser.makeHtml("dasdas");
    $('.preview').html(a);
});</script>
`

**Comment by Integ** [comment]
@stevesgit 并不需要使用 require.js，require() 是 nodejs 的 CommonJS 模块化方案。

**Comment by stevesgit** [comment]
@integ 谢回复，我原以为不需要依赖，那就是依赖nodeJS，我去尝试一下。

**Comment by Integ** [comment]
@stevesgit  我们最近用 coffee 重构了hyperdown.
之前的用法，在最新的代码里可能不适用。

**Comment by stevesgit** [comment]
@Integ 那能贴一下最新的用法吗？现在要用前端实时显示Markdown。对学后端程序员，readme里的介绍过于简单了。3q.

**Comment by Integ** [comment]
@stevesgit 谢邀！
你只要在浏览器里先加载 Parser.js ，然后就可以调用 window.HyperDown 了。

**Comment by stevesgit** [comment]
@Integ  谢作者，按你所述，现已经成功使用。
