### ISSUE TITLE
是否可以做出些调整，如减少依赖？

### ISSUE THREAD

**Issue by hellobbq** [SegmentFault/HyperDown.js#4]
1、md5，就一个uniqid时用到了，是否可以考虑去掉
2、_createClass，真的有必要么？

个人觉得一个类库的话越简单越好

**Comment by Integ** [comment]
为了兼容更多的浏览器，用了 babel 的 polyfill，导致引入了大量的兼容性代码

建议自己动手把第一行 `import 'babel-core/polyfill'` 去掉然后 build 下。

**Comment by hellobbq** [comment]
我是删减了dist文件的一些我不需要的然后就用了，ie8调试发现的问题是_createClass里面的Object.defineProperty有问题就被中断，不能测试下面的兼容问题，

本来想打算替换原本的_createClass方法，不过还是想先看看这边官方会不会有update的动作

**Comment by Integ** [comment]
hyperdown.js 已更新至1.0.1
去除了对第三方库的依赖
因为兼容IE8 需要大量辅助代码，所以放弃IE8了。
