### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by hellobbq** [SegmentFault/HyperDown.js#5]
1、dist 683行，大写的NULL
2、如果出现换行，会出现```<hnull>一级标题</hnull>```的问题
```
# 一级标题 # 
## 二级标题 ##
### 三级标题 ###
```

3、hook的返回，只有下述方法返回自定义数组才正确，不应该是字符串么
```
			converter.hook("afterParseInlineBeforeRelease", function(value){
				value = value[0];
				return [value];
			});
```

4、```aa@aa.com```无法解析

备注：
2不确定是否源码问题，因为我使用方法有略微调整，虽然感觉应该是正确的，替换其它开源类库也是ok的。

另外有个问题：源码同步sf在线版本么？感觉解析结果差别蛮大的，不过想table居中居左居右的bug倒是一样。
个人不太喜欢用国产开源项目，哪怕是bat公司的，特别是这个B，我觉得但凡做开发的都理解我的担忧。我该担忧在公司项目里使用这个类库么

最后感谢开源这么轻巧的项目

**Comment by hellobbq** [comment]
```### 三级标题 ###```使用 beforeParseSh,发现会循环调用2次？

**Comment by Integ** [comment]
谢谢你的反馈，
1，2，3，5，6 已经修复
第 4 个邮件的解析目前只支持前后加了 <>  的邮箱地址如： <aa@aa.com>
