### ISSUE TITLE
table有问题？

### ISSUE THREAD

**Issue by joyqi** [SegmentFault/HyperDown.js#7]
_From @hellobbq on November 7, 2015 12:23_

```
| Left-Aligned  | Center Aligned  | Right Aligned |
| :------------ |:---------------:| -----:|
| col 3 is      | some wordy text | $1600 |
| col 2 is      | centered        |   $12 |
| zebra stripes | are neat        |    $1 |

| Item      | Value |
| --------- | -----:|
| Computer  | $1600 |
| Phone     |   $12 |
| Pipe      |    $1 |
```

找的demo，发现错误

| Left-Aligned  | Center Aligned  | Right Aligned |
| :------------ |:---------------:| -----:|
| col 3 is      | some wordy text | $1600 |
| col 2 is      | centered        |   $12 |
| zebra stripes | are neat        |    $1 |

| Item      | Value |
| --------- | -----:|
| Computer  | $1600 |
| Phone     |   $12 |
| Pipe      |    $1 |

_Copied from original issue: SegmentFault/HyperDown#12_

**Comment by joyqi** [comment]
这个bug在后端没有出现，应该是HyperDown.js的前端bug，我将把它移动到相应的repo处理

**Comment by Integ** [comment]
正在处理

**Comment by Integ** [comment]
hyperdown.js 已经更新
